### ISSUE TITLE
The "no attribute" problem

### ISSUE THREAD

**Issue by li-sky** [li-sky/QQthreads#1]
```
Traceback (most recent call last):
  File "/home/skyli/.local/lib/python2.7/site-packages/qqbot/qqbotcls.py", line 99, in _call
    func(*args, **kwargs)
  File "/home/skyli/.qqbot-tmp/plugins/bot.py", line 23, in onQQMessage
    dict2[str(dict2_index)] = contact[8:]
TypeError: 'Group' object has no attribute '__getitem__'
```

**Comment by li-sky** [comment]
Fixed.
